#                                                           Developed by Ruben_Artz
#
#                                                     (ARTZSTUDIO.DEV @ (C) 2018-2026)

name: 'DeluxeMentions'
version: '${version}'
main: 'artzstudio.dev.mentions.spigot.DeluxeMentions'
authors: [ 'Ruben_Artz', 'Artz Studio' ]
description: 'Amazing resource to mention your players.'
website: 'https://www.spigotmc.org/resources/67248/'
api-version: '1.16'
softdepend: [ 'SuperVanish', 'PremiumVanish', 'PlaceholderAPI', 'BotSentry' ]

commands:
  deluxementions:
    description: 'Mentions main command. Type ''/ms help'' for more information.'
    aliases: [ 'ms' ]
  mention:
    description: 'Disable your mentions or active!'
